services:
  - type: web
    name: qwait-backend
    env: node
    rootDir: qwait-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: web
    name: qwait-arima
    env: python
    rootDir: qwait-arima-service
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT arima_service:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
